# Generated by Django 6.0.5 on 2026-05-27 14:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Escrutinio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.IntegerField()),
                ("is_final", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparando", "Preparando"),
                            ("aberto", "Aberto"),
                            ("encerrado", "Encerrado"),
                        ],
                        default="preparando",
                        max_length=12,
                    ),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("total_voters", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrutinios",
                        to="elections.election",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
                    ),
                ),
            ],
            options={
                "db_table": "escrutinios",
                "ordering": ["number"],
                "unique_together": {("election", "number")},
            },
        ),
        migrations.CreateModel(
            name="BallotSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ballot_sessions",
                        to="elections.voter",
                    ),
                ),
                (
                    "escrutinio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballot_sessions",
                        to="voting.escrutinio",
                    ),
                ),
            ],
            options={
                "db_table": "ballot_sessions",
            },
        ),
        migrations.CreateModel(
            name="ElectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("votes_count", models.IntegerField()),
                ("was_elected", models.BooleanField(default=False)),
                ("tie_at_cutoff", models.BooleanField(default=False)),
                ("tie_resolution", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="elections.candidate"
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="elections.election",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="elections.position"
                    ),
                ),
                (
                    "escrutinio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="voting.escrutinio",
                    ),
                ),
            ],
            options={
                "db_table": "election_results",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("votes_count__gte", 0)),
                        name="election_results_votes_count_gte_0",
                    )
                ],
                "unique_together": {("escrutinio", "candidate")},
            },
        ),
        migrations.CreateModel(
            name="EscrutinioCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="escrutinio_entries",
                        to="elections.candidate",
                    ),
                ),
                (
                    "escrutinio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="voting.escrutinio",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="elections.position"
                    ),
                ),
            ],
            options={
                "db_table": "escrutinio_candidates",
                "unique_together": {("escrutinio", "candidate")},
            },
        ),
        migrations.CreateModel(
            name="EscrutinioPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("vacancies_remaining", models.IntegerField()),
                (
                    "escrutinio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="voting.escrutinio",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="escrutinio_positions",
                        to="elections.position",
                    ),
                ),
            ],
            options={
                "db_table": "escrutinio_positions",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("vacancies_remaining__gte", 0)),
                        name="escrutinio_positions_vacancies_gte_0",
                    )
                ],
                "unique_together": {("escrutinio", "position")},
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="votes",
                        to="elections.candidate",
                    ),
                ),
                (
                    "escrutinio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="votes",
                        to="voting.escrutinio",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="elections.position"
                    ),
                ),
            ],
            options={
                "db_table": "votes",
                "indexes": [
                    models.Index(
                        fields=["escrutinio", "candidate"], name="votes_escruti_d876aa_idx"
                    ),
                    models.Index(
                        fields=["escrutinio", "position"], name="votes_escruti_c1689f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VoterAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("voted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "escrutinio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="voting.escrutinio",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="attendances",
                        to="elections.voter",
                    ),
                ),
            ],
            options={
                "db_table": "voter_attendance",
                "unique_together": {("escrutinio", "voter")},
            },
        ),
    ]
