# Generated by Django 6.0.5 on 2026-05-27 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("scheduled_for", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("pronta", "Pronta"),
                            ("em_andamento", "Em andamento"),
                            ("encerrada", "Encerrada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                (
                    "final_rule",
                    models.CharField(
                        choices=[("manual", "Manual"), ("max_count", "Por máximo de escrutínios")],
                        max_length=10,
                    ),
                ),
                ("max_escrutinios", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elections",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "elections",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("vacancies", models.IntegerField()),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="elections.election",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
                    ),
                ),
            ],
            options={
                "db_table": "positions",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="elections.election",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="elections.position",
                    ),
                ),
            ],
            options={
                "db_table": "candidates",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("cpf_hash", models.CharField(max_length=64)),
                ("cpf_last2", models.CharField(max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voters",
                        to="elections.election",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
                    ),
                ),
            ],
            options={
                "db_table": "voters",
            },
        ),
        migrations.AddIndex(
            model_name="election",
            index=models.Index(
                fields=["organization", "status"], name="elections_organiz_cf940d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="election",
            index=models.Index(
                fields=["organization", "scheduled_for"], name="elections_organiz_d0f2d3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.CheckConstraint(
                condition=models.Q(("vacancies__gte", 1)), name="positions_vacancies_gte_1"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together={("election", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={("position", "name")},
        ),
        migrations.AddIndex(
            model_name="voter",
            index=models.Index(fields=["election", "cpf_hash"], name="voters_electio_83bc48_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="voter",
            unique_together={("election", "cpf_hash")},
        ),
    ]
